# Generated by Django 3.1 on 2020-09-26 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CSI', '0002_auto_20200926_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='file',
            field=models.FileField(blank=True, upload_to='samples'),
        ),
    ]
