# Generated by Django 3.0.3 on 2020-09-27 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CSI', '0003_auto_20200926_2347'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='transcript',
            field=models.TextField(blank=True),
        ),
    ]
